version: '3.0'
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - ${HTTP_HOST}:80
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
  php: 
    build: ./php
    image: m0yuqi/php
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP7_PHP_CONFIG_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP7_FPM_CONFIG_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    cap_add:
      - SYS_PTRACE
    networks:
      - default
    restart: always
  mysql:
    build: ./mysql
    image: m0yuqi/mysql-alpine
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    expose:
      - "3306"
    volumes:
      - /data:/var/lib/mysql
    restart: always
